### ISSUE TITLE
how to run your codes on customized data?

### ISSUE THREAD

**Issue by Holmes-Alan** [rgl-epfl/differentiable-sdf-rendering#5]
how do I use your codes to test on my own collected photos?

**Comment by hrehfeld** [comment]
> Note: All experiments in this paper were done on synthetic data, which means that this repository is not useful as is to reconstruct objects from captured images. This code is meant for researchers working on related problems, not end users.

What are the major steps towards using this on real world data?

**Comment by dvicini** [comment]
Hi,

The code really doesn't support real world data yet. In order to do that, you would need to first estimate the camera parameters. Then, you would want to modify the code to optimize both an SDF and environment illumination, which is something I haven't tried yet.

Delio

**Comment by carlosedubarreto** [comment]
@dvicini this work is amazing and I would like to try to make it work for custom images.

That camera parameters that you say was something that I was missing.
Probably because you dont need to set it up since you are rendering your own images. but can you point out where those camera parameters should be added, or some place that can point me on the right direction?

I think that, instead of defining an angle to render the images I'll have to consider the angle where I import the images.
And I should take into account both camera parameters, i mean the intrinsic and extrinsic calibration, is that correct?

Thanks a lot

**Comment by dvicini** [comment]
You would want to estimate both camera intrinsics and extrinsics and then construct Mitsuba sensors matching those from it. In the code, wherever the sensors are initialized/loaded, you would want to pass the ones matching your real data. 

Another aspect to consider is the background/environment map, which we currently assume to be known. You would want to also optimize for those when working using real data.

**Comment by wenwennnn** [comment]
@carlosedubarreto 
Hi, sorry for bothering you.

I'm about to try something similar and was wondering if your previous attempt was successful~?
