### ISSUE TITLE
jit_optix_init(): libnvoptix.so.1 could not be loaded

### ISSUE THREAD

**Issue by day9011** [rgl-epfl/differentiable-sdf-rendering#8]
system: 5.8.0-63-generic #71~20.04.1-Ubuntu SMP
cuda: 11.3

**Comment by dvicini** [comment]
Hi,
Could you provide some more details? Is this really an issue with this code here or rather a Mitsuba related problem?

Delio

**Comment by day9011** [comment]
Hi, I think this is a Nvidia tools problem that nvdia optix tools cant install automatically. There is no information for nvidia optix tool in document, so I try 6.0.0 and 7.5.0 with this code. But they are invalid.

**Comment by dvicini** [comment]
Can you run some of the Mitsuba 3 examples or tutorials? You should not need to install optix to run Mitsuba or this code base. Mitsuba/DrJit automatically load the optix functionality from the Nvidia driver and don't depend on a local installation.

I will close this issue here, as it seems unrelated to this specific code base.

**Comment by markusheimerl** [comment]
Running "sudo apt install libnvidia-gl-535" worked for me. The driver itself did not ship with optix for me. I am on native Ubuntu 24.04

**Comment by Song-jinshui** [comment]
> Running "sudo apt install libnvidia-gl-535" worked for me. The driver itself did not ship with optix for me. I am on native Ubuntu 24.04

I love you. This is work for me!
